In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv("customers_data.csv")
data=pd.DataFrame(data)
print(data)
print(type(data))

data.head()
data.tail()
data.info()
data.sample()
data.describe()

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
4            1005  Rahul  35.0  Female    Kolkata   80424.0             NaN
...           ...    ...   ...     ...        ...       ...             ...
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0
3049         3607   Riya   NaN  Female      Delhi   67474.0            79.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
4           No
...        ...
3045       Yes
3046       Yes
3047        No
3048       Yes
3049        No

[3050 rows x 8 columns]
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3050 entries, 0 to 3049
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Customer_ID     3050 non-null   int64
 1   Name            3050 non-null   object
 2   Age             2896 non-null   float64
 3   Gender          3050 non-null   object
 4   City            2897 non-null   object
 5   Income          2897 non-null   float64
 6   Spending_Score  2899 non-null   float64
 7   Purchased       3050 non-null   object
dtypes: float64(3), int64(1), object(4)
memory usage: 190.8+ KB

       Customer_ID          Age         Income  Spending_Score
count  3050.000000  2896.000000    2897.000000     2899.000000
mean   2501.971803    38.573895   60570.926821       49.411176
std     865.955930    11.897028   57280.117599       28.829117
min    1001.000000    18.000000   15005.000000        1.000000
25%    1752.250000    29.000000   34622.000000       24.000000
50%    2502.500000    39.000000   57287.000000       50.000000
75%    3252.750000    49.000000   78226.000000       74.000000
max    4000.000000    59.000000  960080.000000       99.000000

In [ ]:
data.shape

(3050, 8)

In [ ]:
data.isnull()

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...
3045,False,False,False,False,False,False,False,False
3046,False,False,False,False,False,False,False,False
3047,False,False,False,False,False,False,False,False
3048,False,False,False,False,False,False,False,False
3049,False,False,True,False,False,False,False,False

In [ ]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3045    False
3046     True
3047     True
3048     True
3049     True
Length: 3050, dtype: bool

In [ ]:
data.sort_values(by="Income",ascending=True)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
2330,3331,Vikas,20.0,Male,Kolkata,15005.0,35.0,Yes
1083,2084,Arjun,40.0,Female,Lucknow,15015.0,39.0,Yes
2541,3542,Neha,39.0,Female,Delhi,15026.0,37.0,No
1671,2672,Riya,49.0,Male,Kolkata,15045.0,52.0,Yes
1038,2039,Aman,55.0,Female,Bangalore,15048.0,15.0,No
...,...,...,...,...,...,...,...,...
2978,3979,Simran,46.0,Female,Mumbai,NaN,43.0,No
2981,3982,Priya,24.0,Male,Lucknow,NaN,3.0,No
3011,2925,Priya,19.0,Female,Kolkata,NaN,50.0,No
3014,1550,Aman,NaN,Male,Mumbai,NaN,86.0,No
3019,1860,Simran,NaN,Female,Lucknow,NaN,98.0,No

In [ ]:
data.isnull().sum()

Customer_ID         0
Name                0
Age               154
Gender              0
City              153
Income            153
Spending_Score    151
Purchased           0
dtype: int64

In [ ]:
data.duplicated().sum()

np.int64(48)

In [ ]:
data["Age"].fillna(data["Age"].median(),inplace=True)
data["Income"].fillna(data["Income"].median())
data["Spending_Score"].fillna(data["Spending_Score"].median())
data["City"].fillna(data["City"].mode()[0])
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
5            1006  Vikas  53.0    Male  Bangalore   90838.0            97.0
...           ...    ...   ...     ...        ...       ...             ...
3044         2170  Vikas  58.0    Male    Lucknow   23520.0            38.0
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
5          Yes
...        ...
3044        No
3045       Yes
3046       Yes
3047        No
3048       Yes

[2488 rows x 8 columns]

/tmp/ipykernel_16886/2434973497.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].median(),inplace=True)

In [ ]:
print(data["Gender"].mode())

0    Female
Name: Gender, dtype: object

In [ ]:
print(data["City"].mode())

0    Lucknow
Name: City, dtype: object

In [ ]:
data["Gender"].fillna(data["Gender"].mode()[0],inplace=True)
data["City"].fillna(data["City"].mode()[0],inplace=True)
print(data)

      Customer_ID   Name   Age  Gender       City    Income  Spending_Score  \
0            1001  Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002  Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003   Neha  45.0  Female      Delhi   16502.0            51.0
3            1004   Aman  38.0  Female    Kolkata   85192.0            19.0
5            1006  Vikas  53.0    Male  Bangalore   90838.0            97.0
...           ...    ...   ...     ...        ...       ...             ...
3044         2170  Vikas  58.0    Male    Lucknow   23520.0            38.0
3045         1085   Neha  58.0  Female  Bangalore  421950.0             9.0
3046         1290  Arjun  31.0  Female     Mumbai   49948.0            98.0
3047         3016   Aman  52.0    Male  Bangalore   90583.0            90.0
3048         2409  Karan  57.0  Female  Bangalore   55910.0            14.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
5          Yes
...        ...
3044        No
3045       Yes
3046       Yes
3047        No
3048       Yes

[2488 rows x 8 columns]

/tmp/ipykernel_16886/762969882.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Gender"].fillna(data["Gender"].mode()[0],inplace=True)
/tmp/ipykernel_16886/762969882.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["City"].fillna(data["City"].mode()[0],inplace=True)

In [ ]:
data.drop_duplicates(inplace=True)
data.head(7)

,Customer_ID,Name,Age,Gender,City,Income,Spending_Score,Purchased
0,1001,Rahul,41.0,Male,Delhi,99579.0,99.0,Yes
1,1002,Priya,55.0,Female,Bangalore,15255.0,44.0,Yes
2,1003,Neha,45.0,Female,Delhi,16502.0,51.0,Yes
3,1004,Aman,38.0,Female,Kolkata,85192.0,19.0,Yes
5,1006,Vikas,53.0,Male,Bangalore,90838.0,97.0,Yes
6,1007,Karan,52.0,Male,Mumbai,85966.0,66.0,Yes
7,1008,Rahul,26.0,Male,Bangalore,56366.0,13.0,No

In [ ]:
data["Purchased"]=data["Purchased"].astype("category")
print(data)

      Customer_ID    Name   Age  Gender       City    Income  Spending_Score  \
0            1001   Rahul  41.0    Male      Delhi   99579.0            99.0
1            1002   Priya  55.0  Female  Bangalore   15255.0            44.0
2            1003    Neha  45.0  Female      Delhi   16502.0            51.0
3            1004    Aman  38.0  Female    Kolkata   85192.0            19.0
5            1006   Vikas  53.0    Male  Bangalore   90838.0            97.0
...           ...     ...   ...     ...        ...       ...             ...
2997         3998   Arjun  38.0  Female     Mumbai   72295.0            87.0
2998         3999  Simran  39.0    Male     Mumbai   48939.0            31.0
2999         4000   Rahul  52.0  Female    Lucknow   63599.0            36.0
3029         3795   Vikas  26.0  Female  Bangalore   93798.0            70.0
3045         1085    Neha  58.0  Female  Bangalore  421950.0             9.0

     Purchased
0          Yes
1          Yes
2          Yes
3          Yes
5          Yes
...        ...
2997       Yes
2998        No
2999        No
3029       Yes
3045       Yes

[2448 rows x 8 columns]

In [ ]:
Q1=data['Spending_Score'].quantile(0.25)
Q3=data['Spending_Score'].quantile(0.75)
IQR=Q3-Q1
print(Q1,Q3,IQR)

24.0 74.0 50.0